const NAVIGATE = 'NAVIGATE';
const ADDLIST = 'ADDLIST';
const ADDITEM = 'ADDITEM';
const DELETEITEM = 'DELETEITEM';
const DELETELIST = 'DELETELIST';

export {
    NAVIGATE,
    ADDITEM,
    ADDLIST,
    DELETEITEM,
    DELETELIST,
};