const SETLISTS = 'SETLISTS';
const ADDLIST = 'ADDLIST';
const ADDITEM = 'ADDITEM';
const DELETEITEM = 'DELETEITEM';
const DELETELIST = 'DELETELIST';
const CHECKITEM = 'CHECKITEM';

export {
    SETLISTS,
    ADDITEM,
    ADDLIST,
    DELETEITEM,
    DELETELIST,
    CHECKITEM
};