const ADDACTIVITY = 'ADDACTIVITY';
const SAVESETTINGS = 'SAVESETTINGS';
const SETINFO = 'SETINFO';
const SAVEINITIALINFO = 'SAVEINITIALINFO';

export {
    ADDACTIVITY,
    SAVESETTINGS,
    SETINFO,
    SAVEINITIALINFO
};