const ADDACTIVITY = 'ADDACTIVITY';
const DELETEACTIVITY = 'DELETEACTIVITY';
const SAVESETTINGS = 'SAVESETTINGS';
const SETINFO = 'SETINFO';
const UPDATETROPHIES = 'UPDATETROPHIES';
const UPDATEGOALS = 'UPDATEGOALS';

export {
    ADDACTIVITY,
    DELETEACTIVITY,
    SAVESETTINGS,
    SETINFO,
    UPDATETROPHIES,
    UPDATEGOALS
};